#!/usr/bin/env bash
set -e

# Generated by service-tunnel.sh
CONNECTIONS=(
"mongodb://4ddd27279a7b5d3c3e9d91a5cbbb8c29:0f753ec04e15d0f16f6b6cabdc25ccb2@localhost:27018/95f43b215bc706f4"
"mongodb://b788d3fee1c4c1ad8050153b86e60c2c:10174140dce13ff9064f03acdae13b21@localhost:27021/e7a888ec3bec00b0"
"mongodb://2ba94263a6df0e5ff0cca8a0c888180d:59d4e7fec38feddb8d4c8af95446fc09@localhost:27024/f5da3b81b9d8dc87"
"mongodb://b077e25929c116278c4019a75dcd8cc6:a6d15902aa383ac0d72562a6052f73a1@localhost:27027/c890b216188e4716"
"mongodb://839e52af8fcdd5b152b4c8f5eadf2450:0b155e1e1aa701dba6db9f1e87ecda57@localhost:27032/3f88c66cadc5d8e6"
"mongodb://d9513b3186ef06deb77c5a59f303a502:c1515f04f05083362ab843128796c4ab@localhost:27033/c22fc51736896366"
"mongodb://1697956ee8907a029d18d090afcf331f:26c0405a2f3a739ca3aea947d6892efc@localhost:27038/016951e98dd50a00"
)

if [[ -z $YEAR ]]; then
  YEAR=$(date +"%Y")
fi
if [[ -z $MONTH ]]; then
  MONTH=$(date +"%m")
fi

EVAL_SCRIPT="db.getCollectionNames().forEach(function(collectionName) {
    if ( collectionName.match(/abacus-.*$YEAR$MONTH/) ) {
      var result = db.getCollection(collectionName).remove({
        organization_id: { \$in:[
          '08d38300-bcfe-40c8-b89d-d6ecc1b84a6a',
          'b71fc53b-7518-4d2b-b8da-00aaed032e0c',
          'b9bd6457-1b8e-421f-bcb1-3f5259ece518',
          '0f1a2a1e-6db5-46ee-8d66-c3e41167711d'
        ]}
      });
      print(collectionName + ' ' + result);
    }
})"

echo "$EVAL_SCRIPT"

for CON in "${CONNECTIONS[@]}"; do
  mongo "$CON" --quiet --eval "$EVAL_SCRIPT" &
done

wait

echo "Done.                                                   "
